Análise de similaridade de strings

In [1]:
from google.colab import drive
drive.mount('/content/drive')
DATA_PATH = "/content/drive/MyDrive/Docencia/IDP/Dados"

Mounted at /content/drive

In [ ]:
!pip install distance

In [ ]:
import distance
import pandas as pd
import os

In [ ]:
s1, s2 = "Ricardo Akl", "Ricardo A"
distance.levenshtein(s1, s2)

2

In [ ]:
distance.nlevenshtein(s1,s2, method=1)

0.18181818181818182

Vamos usar em casos reais. Na questão do CNAE.

In [ ]:
df_cnae_fornecedores = pd.read_pickle(os.path.join(DATA_PATH, "cnaes_transf.pkl"))
df_cnae_fornecedores

           id                                          descricao codigo_longo
0      111301                                   CULTIVO DE ARROZ    0111-3/01
1      111302                                   CULTIVO DE MILHO    0111-3/02
2      111303                                   CULTIVO DE TRIGO    0111-3/03
3      111399  CULTIVO DE OUTROS CEREAIS NAO ESPECIFICADOS AN...    0111-3/99
4      112101                        CULTIVO DE ALGODAO HERBACEO    0112-1/01
...       ...                                                ...          ...
1343  9609207                   ALOJAMENTO DE ANIMAIS DOMESTICOS    9609-2/07
1344  9609208      HIGIENE E EMBELEZAMENTO DE ANIMAIS DOMESTICOS    9609-2/08
1345  9609299  OUTRAS ATIVIDADES DE SERVICOS PESSOAIS NAO ESP...    9609-2/99
1346  9700500                                SERVICOS DOMESTICOS    9700-5/00
1347  9900800  ORGANISMOS INTERNACIONAIS E OUTRAS INSTITUICOE...    9900-8/00

[1348 rows x 3 columns]

In [ ]:
import unicodedata
def padroniza_str(str):
  nfd = unicodedata.normalize("NFD", str)
  return nfd.encode("ascii", "ignore").decode("utf-8").upper()

In [ ]:
df_cnae = pd.read_csv(os.path.join(DATA_PATH,'CNAERFB.CSV'),
                      sep=';',
                      encoding='latin-1',
                      names=['id_cnae', 'desc_cnae'])
df_cnae.desc_cnae = pd.Series(map(padroniza_str, df_cnae.desc_cnae))
df_cnae

      id_cnae                                          desc_cnae
0      111301                                   CULTIVO DE ARROZ
1      111302                                   CULTIVO DE MILHO
2      111303                                   CULTIVO DE TRIGO
3      111399  CULTIVO DE OUTROS CEREAIS NAO ESPECIFICADOS AN...
4      112101                        CULTIVO DE ALGODAO HERBACEO
...       ...                                                ...
1354  9609208      HIGIENE E EMBELEZAMENTO DE ANIMAIS DOMESTICOS
1355  9609299  OUTRAS ATIVIDADES DE SERVICOS PESSOAIS NAO ESP...
1356  9700500                                SERVICOS DOMESTICOS
1357  9900800  ORGANISMOS INTERNACIONAIS E OUTRAS INSTITUICOE...
1358  8888888                  ATIVIDADE ECONONICA NAO INFORMADA

[1359 rows x 2 columns]

In [ ]:
df_merge_cnae = df_cnae_fornecedores.merge(df_cnae, how='left',left_on='id', right_on='id_cnae')
condicao = df_merge_cnae.descricao == df_merge_cnae.desc_cnae
df_merge_cnae[condicao]

,id,descricao,codigo_longo,id_cnae,desc_cnae
0,111301,CULTIVO DE ARROZ,0111-3/01,111301,CULTIVO DE ARROZ
1,111302,CULTIVO DE MILHO,0111-3/02,111302,CULTIVO DE MILHO
2,111303,CULTIVO DE TRIGO,0111-3/03,111303,CULTIVO DE TRIGO
3,111399,CULTIVO DE OUTROS CEREAIS NAO ESPECIFICADOS AN...,0111-3/99,111399,CULTIVO DE OUTROS CEREAIS NAO ESPECIFICADOS AN...
4,112101,CULTIVO DE ALGODAO HERBACEO,0112-1/01,112101,CULTIVO DE ALGODAO HERBACEO
...,...,...,...,...,...
1343,9609207,ALOJAMENTO DE ANIMAIS DOMESTICOS,9609-2/07,9609207,ALOJAMENTO DE ANIMAIS DOMESTICOS
1344,9609208,HIGIENE E EMBELEZAMENTO DE ANIMAIS DOMESTICOS,9609-2/08,9609208,HIGIENE E EMBELEZAMENTO DE ANIMAIS DOMESTICOS
1345,9609299,OUTRAS ATIVIDADES DE SERVICOS PESSOAIS NAO ESP...,9609-2/99,9609299,OUTRAS ATIVIDADES DE SERVICOS PESSOAIS NAO ESP...
1346,9700500,SERVICOS DOMESTICOS,9700-5/00,9700500,SERVICOS DOMESTICOS
1347,9900800,ORGANISMOS INTERNACIONAIS E OUTRAS INSTITUICOE...,9900-8/00,9900800,ORGANISMOS INTERNACIONAIS E OUTRAS INSTITUICOE...

In [ ]:
df_merge_cnae[~condicao]

,id,descricao,codigo_longo,id_cnae,desc_cnae
171,1011205,"MATADOURO - ABATE DE RESES SOB CONTRATO, EXCET...",1011-2/05,1011205,MATADOURO - ABATE DE RESES SOB CONTRATO - EXCE...
257,1412601,"CONFECCAO DE PECAS DO VESTUARIO, EXCETO ROUPAS...",1412-6/01,1412601,"CONFECCAO DE PECAS DE VESTUARIO, EXCETO ROUPAS..."
278,1610204,SERRARIAS SEM DESDOBRAMENTO DE MADEIRA EM BRUT...,1610-2/04,1610204,SERRARIAS SEM DESDOBRAMENTO DE MADEIRA EM BRUT...
294,1741902,"FABRICACAO DE PRODUTOS DE PAPEL, CARTOLINA, PA...",1741-9/02,1741902,"FABRICACAO DE PRODUTOS DE PAPEL, CARTOLINA, PA..."
403,2449103,PRODUCAO DE ANODOS PARA GALVANOPLASTIA,2449-1/03,2449103,FABRICACAO DE ANODOS PARA GALVANOPLASTIA
463,2814302,FABRICACAO DE COMPRESSORES PARA USO NAO-INDUST...,2814-3/02,2814302,FABRICACAO DE COMPRESSORES PARA USO NAO INDUST...
616,4212000,CONSTRUCAO DE OBRAS-DE-ARTE ESPECIAIS,4212-0/00,4212000,CONSTRUCAO DE OBRAS DE ARTE ESPECIAIS
641,4329102,INSTALACAO DE EQUIPAMENTOS PARA ORIENTACAO A N...,4329-1/02,4329102,INSTALACAO DE EQUIPAMENTOS PARA ORIENTACAO A N...
686,4541206,COMERCIO A VAREJO DE PECAS E ACESSORIOS NOVOS ...,4541-2/06,4541206,COMERCIO A VAREJO DE PECAS E ACESSORIOS NOVOS ...
785,4679603,"COMERCIO ATACADISTA DE VIDROS, ESPELHOS E VITRAIS",4679-6/03,4679603,"COMERCIO ATACADISTA DE VIDROS, ESPELHOS, VITRA..."
788,4681801,"COMERCIO ATACADISTA DE ALCOOL CARBURANTE, BIOD...",4681-8/01,4681801,"COMERCIO ATACADISTA DE ALCOOL CARBURANTE, BIOD..."
789,4681802,COMERCIO ATACADISTA DE COMBUSTIVEIS REALIZADO ...,4681-8/02,4681802,COMERCIO ATACADISTA DE COMBUSTIVEIS REALIZADO ...
906,4930201,"TRANSPORTE RODOVIARIO DE CARGA, EXCETO PRODUTO...",4930-2/01,4930201,"TRANSPORTE RODOVIARIO DE CARGA, EXCETO PRODUTO..."
944,5231103,GESTAO DE TERMINAIS AQUAVIARIOS,5231-1/03,5231103,GESTAO DE TERMINAIS AQUAVIARIOS
957,5310502,ATIVIDADES DEFRANQUEADAS E PERMISSIONARIAS DO ...,5310-5/02,5310502,ATIVIDADES DE FRANQUEADAS DO CORREIO NACIONAL
982,5819100,"EDICAO DE CADASTROS, LISTAS E OUTROS PRODUTOS ...",5819-1/00,5819100,"EDICAO DE CADASTROS, LISTAS E DE OUTROS PRODUT..."
988,5829800,"EDICAO INTEGRADA A IMPRESSAO DE CADASTROS, LIS...",5829-8/00,5829800,"EDICAO INTEGRADA A IMPRESSAO DE CADASTROS, LIS..."
1003,6110802,SERVICOS DE REDES DE TRANSPORTE DE TELECOMUNIC...,6110-8/02,6110802,SERVICOS DE REDES DE TRANSPORTES DE TELECOMUNI...
1153,7733100,ALUGUEL DE MAQUINAS E EQUIPAMENTOS PARA ESCRIT...,7733-1/00,7733100,ALUGUEL DE MAQUINAS E EQUIPAMENTOS PARA ESCRIT...
1184,8291100,ATIVIDADES DE COBRANCA E INFORMACOES CADASTRAIS,8291-1/00,8291100,ATIVIDADES DE COBRANCAS E INFORMACOES CADASTRAIS
1250,8640213,SERVICOS DE LITOTRIPSIA,8640-2/13,8640213,SERVICOS DE LITOTRIPCIA
1263,8690902,ATIVIDADES DE BANCOS DE LEITE HUMANO,8690-9/02,8690902,ATIVIDADES DE BANCO DE LEITE HUMANO
1271,8711505,CONDOMINIOS RESIDENCIAIS PARA IDOSOS,8711-5/05,8711505,CONDOMINIOS RESIDENCIAIS PARA IDOSOS E DEFICIE...
1274,8720499,ATIVIDADES DE ASSISTENCIA PSICOSSOCIAL E A SAU...,8720-4/99,8720499,ATIVIDADES DE ASSISTENCIA PSICOSSOCIAL E A SAU...
1279,8888888,ATIVIDADE NAO INFORMADA,8888-8/88,8888888,ATIVIDADE ECONONICA NAO INFORMADA
1286,9001999,"ARTES CENICAS, ESPETACULOS E ATIVIDADES COMPLE...",9001-9/99,9001999,"ARTES CENICAS, ESPETACULOS E ATIVIDADES COMPLE..."
1288,9002702,RESTAURACAO DE OBRAS DE ARTE,9002-7/02,9002702,RESTAURACAO DE OBRAS-DE-ARTE

In [ ]:
qtd_ok = len(df_merge_cnae[condicao])
print(qtd_ok)
qtd_ok = len(df_merge_cnae[~condicao])
print(qtd_ok)

1321
27

In [ ]:
df_diff = df_merge_cnae[~condicao][['descricao', 'desc_cnae']]
df_diff

,descricao,desc_cnae
171,"MATADOURO - ABATE DE RESES SOB CONTRATO, EXCET...",MATADOURO - ABATE DE RESES SOB CONTRATO - EXCE...
257,"CONFECCAO DE PECAS DO VESTUARIO, EXCETO ROUPAS...","CONFECCAO DE PECAS DE VESTUARIO, EXCETO ROUPAS..."
278,SERRARIAS SEM DESDOBRAMENTO DE MADEIRA EM BRUT...,SERRARIAS SEM DESDOBRAMENTO DE MADEIRA EM BRUT...
294,"FABRICACAO DE PRODUTOS DE PAPEL, CARTOLINA, PA...","FABRICACAO DE PRODUTOS DE PAPEL, CARTOLINA, PA..."
403,PRODUCAO DE ANODOS PARA GALVANOPLASTIA,FABRICACAO DE ANODOS PARA GALVANOPLASTIA
463,FABRICACAO DE COMPRESSORES PARA USO NAO-INDUST...,FABRICACAO DE COMPRESSORES PARA USO NAO INDUST...
616,CONSTRUCAO DE OBRAS-DE-ARTE ESPECIAIS,CONSTRUCAO DE OBRAS DE ARTE ESPECIAIS
641,INSTALACAO DE EQUIPAMENTOS PARA ORIENTACAO A N...,INSTALACAO DE EQUIPAMENTOS PARA ORIENTACAO A N...
686,COMERCIO A VAREJO DE PECAS E ACESSORIOS NOVOS ...,COMERCIO A VAREJO DE PECAS E ACESSORIOS NOVOS ...
785,"COMERCIO ATACADISTA DE VIDROS, ESPELHOS E VITRAIS","COMERCIO ATACADISTA DE VIDROS, ESPELHOS, VITRA..."
788,"COMERCIO ATACADISTA DE ALCOOL CARBURANTE, BIOD...","COMERCIO ATACADISTA DE ALCOOL CARBURANTE, BIOD..."
789,COMERCIO ATACADISTA DE COMBUSTIVEIS REALIZADO ...,COMERCIO ATACADISTA DE COMBUSTIVEIS REALIZADO ...
906,"TRANSPORTE RODOVIARIO DE CARGA, EXCETO PRODUTO...","TRANSPORTE RODOVIARIO DE CARGA, EXCETO PRODUTO..."
944,GESTAO DE TERMINAIS AQUAVIARIOS,GESTAO DE TERMINAIS AQUAVIARIOS
957,ATIVIDADES DEFRANQUEADAS E PERMISSIONARIAS DO ...,ATIVIDADES DE FRANQUEADAS DO CORREIO NACIONAL
982,"EDICAO DE CADASTROS, LISTAS E OUTROS PRODUTOS ...","EDICAO DE CADASTROS, LISTAS E DE OUTROS PRODUT..."
988,"EDICAO INTEGRADA A IMPRESSAO DE CADASTROS, LIS...","EDICAO INTEGRADA A IMPRESSAO DE CADASTROS, LIS..."
1003,SERVICOS DE REDES DE TRANSPORTE DE TELECOMUNIC...,SERVICOS DE REDES DE TRANSPORTES DE TELECOMUNI...
1153,ALUGUEL DE MAQUINAS E EQUIPAMENTOS PARA ESCRIT...,ALUGUEL DE MAQUINAS E EQUIPAMENTOS PARA ESCRIT...
1184,ATIVIDADES DE COBRANCA E INFORMACOES CADASTRAIS,ATIVIDADES DE COBRANCAS E INFORMACOES CADASTRAIS
1250,SERVICOS DE LITOTRIPSIA,SERVICOS DE LITOTRIPCIA
1263,ATIVIDADES DE BANCOS DE LEITE HUMANO,ATIVIDADES DE BANCO DE LEITE HUMANO
1271,CONDOMINIOS RESIDENCIAIS PARA IDOSOS,CONDOMINIOS RESIDENCIAIS PARA IDOSOS E DEFICIE...
1274,ATIVIDADES DE ASSISTENCIA PSICOSSOCIAL E A SAU...,ATIVIDADES DE ASSISTENCIA PSICOSSOCIAL E A SAU...
1279,ATIVIDADE NAO INFORMADA,ATIVIDADE ECONONICA NAO INFORMADA
1286,"ARTES CENICAS, ESPETACULOS E ATIVIDADES COMPLE...","ARTES CENICAS, ESPETACULOS E ATIVIDADES COMPLE..."
1288,RESTAURACAO DE OBRAS DE ARTE,RESTAURACAO DE OBRAS-DE-ARTE

In [ ]:
distance.nlevenshtein(df_diff.descricao, df_diff.desc_cnae, method=1)

TypeError: map() must have at least two arguments.

In [ ]:
def lev_method2(str1, str2):
    x = distance.nlevenshtein(str1, str2, method=2)
    return x

In [ ]:
df_diff['dist_lev'] = list(map(lev_method2, df_diff.descricao,df_diff.desc_cnae))
df_diff.sort_values(by='dist_lev',ascending=False)

,descricao,desc_cnae,dist_lev
1271,CONDOMINIOS RESIDENCIAIS PARA IDOSOS,CONDOMINIOS RESIDENCIAIS PARA IDOSOS E DEFICIE...,0.379310
1279,ATIVIDADE NAO INFORMADA,ATIVIDADE ECONONICA NAO INFORMADA,0.303030
957,ATIVIDADES DEFRANQUEADAS E PERMISSIONARIAS DO ...,ATIVIDADES DE FRANQUEADAS DO CORREIO NACIONAL,0.301587
785,"COMERCIO ATACADISTA DE VIDROS, ESPELHOS E VITRAIS","COMERCIO ATACADISTA DE VIDROS, ESPELHOS, VITRA...",0.216667
294,"FABRICACAO DE PRODUTOS DE PAPEL, CARTOLINA, PA...","FABRICACAO DE PRODUTOS DE PAPEL, CARTOLINA, PA...",0.210145
1274,ATIVIDADES DE ASSISTENCIA PSICOSSOCIAL E A SAU...,ATIVIDADES DE ASSISTENCIA PSICOSSOCIAL E A SAU...,0.154321
403,PRODUCAO DE ANODOS PARA GALVANOPLASTIA,FABRICACAO DE ANODOS PARA GALVANOPLASTIA,0.150000
788,"COMERCIO ATACADISTA DE ALCOOL CARBURANTE, BIOD...","COMERCIO ATACADISTA DE ALCOOL CARBURANTE, BIOD...",0.085366
1288,RESTAURACAO DE OBRAS DE ARTE,RESTAURACAO DE OBRAS-DE-ARTE,0.071429
616,CONSTRUCAO DE OBRAS-DE-ARTE ESPECIAIS,CONSTRUCAO DE OBRAS DE ARTE ESPECIAIS,0.054054
982,"EDICAO DE CADASTROS, LISTAS E OUTROS PRODUTOS ...","EDICAO DE CADASTROS, LISTAS E DE OUTROS PRODUT...",0.052632
1250,SERVICOS DE LITOTRIPSIA,SERVICOS DE LITOTRIPCIA,0.043478
988,"EDICAO INTEGRADA A IMPRESSAO DE CADASTROS, LIS...","EDICAO INTEGRADA A IMPRESSAO DE CADASTROS, LIS...",0.037975
789,COMERCIO ATACADISTA DE COMBUSTIVEIS REALIZADO ...,COMERCIO ATACADISTA DE COMBUSTIVEIS REALIZADO ...,0.036145
278,SERRARIAS SEM DESDOBRAMENTO DE MADEIRA EM BRUT...,SERRARIAS SEM DESDOBRAMENTO DE MADEIRA EM BRUT...,0.032258
171,"MATADOURO - ABATE DE RESES SOB CONTRATO, EXCET...",MATADOURO - ABATE DE RESES SOB CONTRATO - EXCE...,0.031250
944,GESTAO DE TERMINAIS AQUAVIARIOS,GESTAO DE TERMINAIS AQUAVIARIOS,0.031250
1263,ATIVIDADES DE BANCOS DE LEITE HUMANO,ATIVIDADES DE BANCO DE LEITE HUMANO,0.027778
1184,ATIVIDADES DE COBRANCA E INFORMACOES CADASTRAIS,ATIVIDADES DE COBRANCAS E INFORMACOES CADASTRAIS,0.020833
1153,ALUGUEL DE MAQUINAS E EQUIPAMENTOS PARA ESCRIT...,ALUGUEL DE MAQUINAS E EQUIPAMENTOS PARA ESCRIT...,0.019608
1003,SERVICOS DE REDES DE TRANSPORTE DE TELECOMUNIC...,SERVICOS DE REDES DE TRANSPORTES DE TELECOMUNI...,0.016949
463,FABRICACAO DE COMPRESSORES PARA USO NAO-INDUST...,FABRICACAO DE COMPRESSORES PARA USO NAO INDUST...,0.014286
686,COMERCIO A VAREJO DE PECAS E ACESSORIOS NOVOS ...,COMERCIO A VAREJO DE PECAS E ACESSORIOS NOVOS ...,0.013158
906,"TRANSPORTE RODOVIARIO DE CARGA, EXCETO PRODUTO...","TRANSPORTE RODOVIARIO DE CARGA, EXCETO PRODUTO...",0.012500
641,INSTALACAO DE EQUIPAMENTOS PARA ORIENTACAO A N...,INSTALACAO DE EQUIPAMENTOS PARA ORIENTACAO A N...,0.012048
257,"CONFECCAO DE PECAS DO VESTUARIO, EXCETO ROUPAS...","CONFECCAO DE PECAS DE VESTUARIO, EXCETO ROUPAS...",0.011765
1286,"ARTES CENICAS, ESPETACULOS E ATIVIDADES COMPLE...","ARTES CENICAS, ESPETACULOS E ATIVIDADES COMPLE...",0.011628